version: '3'
services:
  web:
    build: ./
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy
  database:
    image: 'postgres:16.2'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - ALLOW_IP_RANGE='0.0.0.0/0'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
